export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST'
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS'
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL'

export const EXTRACT_BOOKS_REQUEST = 'EXTRACT_BOOKS_REQUEST'
export const EXTRACT_BOOKS_SUCCESS = 'EXTRACT_BOOKS_SUCCESS'
export const EXTRACT_BOOKS_FAIL = 'EXTRACT_BOOKS_FAIL'
