export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST'
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS'
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL'

export const BOOK_DETAILS_REQUEST = 'BOOK_DETAILS_REQUEST'
export const BOOK_DETAILS_SUCCESS = 'BOOK_DETAILS_SUCCESS'
export const BOOK_DETAILS_FAIL = 'BOOK_DETAILS_FAIL'

export const EXTRACT_BOOKS_REQUEST = 'EXTRACT_BOOKS_REQUEST'
export const EXTRACT_BOOKS_SUCCESS = 'EXTRACT_BOOKS_SUCCESS'
export const EXTRACT_BOOKS_FAIL = 'EXTRACT_BOOKS_FAIL'
export const EXTRACT_BOOKS_RESET = 'EXTRACT_BOOKS_RESET'
